# <center> Tensorflow Maths Fundamentals

## Tensorflow Basic Concepts

TensorFlow gets its name from **tensors**, which are arrays of arbitrary dimensionality. 

Using TensorFlow, you can manipulate tensors with a very high number of dimensions. That said, most of the time you will work with one or more of the following low-dimensional tensors:

- A scalar is a 0-d array (a 0th-order tensor). For example, "Howdy" or 5
- A vector is a 1-d array (a 1st-order tensor). For example, [2, 3, 5, 7, 11] or [5]
- A matrix is a 2-d array (a 2nd-order tensor). For example, [[3.1, 8.2, 5.9][4.3, -2.7, 6.5]]

 TensorFlow operations create, destroy, and manipulate tensors. Most of the lines of code in a typical TensorFlow program are operations.

A TensorFlow **graph** (also known as a computational graph or a dataflow graph) is a graph data structure.

A graph's nodes are operations (in TensorFlow, every operation is associated with a graph). Many TensorFlow programs consist of a single graph, but TensorFlow programs may optionally create multiple graphs. A graph's nodes are operations; a graph's edges are tensors. Tensors flow through the graph, manipulated at each node by an operation. The output tensor of one operation often becomes the input tensor to a subsequent operation. 

**Tensors** can be stored in the graph as **constants** or **variables**.
- Constants hold tensors whose values can't change, while variables hold tensors whose values can change

To define a constant, use the **tf.constant** operator and pass in its value. For example:

In [17]:
import tensorflow as tf
x = tf.constant(5)

You can create a variable like this:

In [18]:
y = tf.Variable([5])

You can create the variable first and then subsequently assign a value like this:


In [19]:
y = tf.Variable([0])
y = y.assign([5])

## Basic Mathematical Functions in Tensorflow :

## Arithmetic Operators

In [20]:
# Arithmetic operators: + - * /% 
tf.add(x, y, name = None) # adder (support Broadcasting)
tf.subtract(x, y, name = None) # subtraction
tf.multiply(x, y, name = None) # multiplication
tf.divide(x, y, name = None) # floating point division, and the floating point (to python3 division)


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([1.])>

In [24]:
# Refers to the number of operator power: ^ ^ 2 ^ 0.5 e ^ ln 
tf.pow (x, y, name = None) # a power of
tf.square (x, name = None) # square
tf.sqrt (x, name = None) # square root, must pass a plurality of floating or
tf.exp (x, name = None) # e calculation of power
tf.log (x, name = None) # e raised, must pass a plurality of floating or


<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [30]:
# Take sign, negative, the inverse of the absolute value, approximately, the larger of two numbers / small
tf.negative (x, name = None) # negate (y = -x).
tf.sign (x, name = None) # Returns the symbol x
tf.reciprocal (x, name = None) # taking the inverse
tf.abs (x, name = None) # absolute value
tf.round (x, name = None) # rounding
tf.ceil (x, name = None) # rounding up
tf.floor (x, name = None) # rounded down
tf.rint (x, name = None) # rounded to the nearest integer 
tf.maximum (x, y, name = None) # returns the maximum of two tensor (x> y x:? y)
tf.minimum (x, y, name = None) # returns the minimum value (x <y x?: y) of two tensor


<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>

In [ ]:
# Trigonometric and inverse trigonometric
tf.cos(x, name=None)    
tf.sin(x, name=None)    
tf.tan(x, name=None)    
tf.acos(x, name=None)
tf.asin(x, name=None)
tf.atan(x, name=None)  

In [43]:
# Other 
tf.div (x, y, name = None) # python 2.7 division, x / y -> int or x / float (y) -> float
tf.truediv (x, y, name = None) # python 3 division, x / y -> float
tf.floordiv (x, y, name = None) # python 3 division, x // y -> int
tf.realdiv(x, y, name=None)
tf.truncatediv(x, y, name=None)
tf.floor_div(x, y, name=None)
tf.truncatemod(x, y, name=None)
tf.floormod(x, y, name=None)
tf.cross(x, y, name=None)
tf.add_n(inputs, name=None)  # inputs: A list of Tensor objects, each with same shape and type
tf.squared_difference(x, y, name=None)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0])>